'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabasePublic } from '@/lib/supabase'
import seed from '@/data/dashboard_v8_seed.json'

const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0)
const num=(n:number)=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(n)||0)
const pct=(n:number)=>`${((Number(n)||0)*100).toFixed(1)}%`
const shortRp=(n:number)=>{const x=Number(n)||0;if(x>=1e12)return `Rp${(x/1e12).toFixed(2)} T`;if(x>=1e9)return `Rp${(x/1e9).toFixed(2)} M`;if(x>=1e6)return `Rp${(x/1e6).toFixed(1)} Jt`;return rupiah(x)}

type Row=any
type SortKey='pokok'|'pnbp'|'frekuensi'|'lot'

export default function Dashboard(){
 const [master,setMaster]=useState<Row[]>([]),[kinerja,setKinerja]=useState<Row[]>([]),[targets,setTargets]=useState<Row[]>([]),[inactive,setInactive]=useState<Row[]>([])
 const [loading,setLoading]=useState(true),[error,setError]=useState('')
 const [kanwilFilter,setKanwilFilter]=useState('ALL'),[metric,setMetric]=useState<SortKey>('pokok'),[status,setStatus]=useState('ALL'),[search,setSearch]=useState('')
 const [chartMode,setChartMode]=useState<'pokok'|'pnbp'|'produktif'>('pokok'),[channelYear,setChannelYear]=useState<'2025'|'2024'>('2025')
 const [histSort,setHistSort]=useState<'kanwil'|'pokok2023'|'pnbp2023'|'pokok2024'|'pnbp2024'|'pokok2025'|'pnbp2025'>('pokok2025'),[histDesc,setHistDesc]=useState(true)

 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const db=supabasePublic();const [m,k,t,i]=await Promise.all([
  db.from('pl2_master').select('id,nama,kanwil,status,wilayah_jabatan,deals').order('nama'),
  db.from('pl2_kinerja').select('pl2_id,nama,kanwil,pokok,pnbp,frekuensi,lot,produktif').eq('period','2026-07').order('pokok',{ascending:false}),
  db.from('pl2_target_kanwil').select('kanwil,period,target_pokok,target_pnbp').eq('period','2026-07').order('kanwil'),
  db.from('pl2_kinerja_inactive').select('nama,kanwil,pokok,pnbp,frekuensi,lot,status,keterangan').eq('period','2026-07').order('nama')
 ]);if(!alive)return;const errs=[m.error,k.error,t.error,i.error].filter(Boolean);if(errs.length)setError(errs.map((e:any)=>e.message).join(' | '));setMaster(m.data??[]);setKinerja(k.data??[]);setTargets(t.data??[]);setInactive(i.data??[]);setLoading(false)})();return()=>{alive=false}},[])

 const byId=useMemo(()=>new Map(kinerja.map(r=>[r.pl2_id,r])),[kinerja])
 const individual=useMemo(()=>master.map(m=>{const k=byId.get(m.id);return {...m,...(k||{}),hasData:Boolean(k && (Number(k.pokok)||Number(k.pnbp)||Number(k.frekuensi)||Number(k.lot))),pokok:Number(k?.pokok)||0,pnbp:Number(k?.pnbp)||0,frekuensi:Number(k?.frekuensi)||0,lot:Number(k?.lot)||0,produktif:Number(k?.produktif)||0}}),[master,byId])
 const kanwilList=useMemo(()=>Array.from(new Set(master.map(r=>String(r.kanwil||'').trim()).filter(Boolean))).sort(),[master])
 const activeMaster=useMemo(()=>master.filter(r=>String(r.status||'').trim().toLowerCase()==='aktif'),[master])
 const activeIndividual=useMemo(()=>individual.filter(r=>String(r.status||'').trim().toLowerCase()==='aktif'),[individual])
 const inactiveRows=useMemo(()=>inactive.map((r,i)=>({id:`inactive-${i}-${r.nama}`,nama:r.nama,kanwil:r.kanwil,status:'Tidak Aktif',wilayah_jabatan:'-',deals:'-',pokok:Number(r.pokok)||0,pnbp:Number(r.pnbp)||0,frekuensi:Number(r.frekuensi)||0,lot:Number(r.lot)||0,produktif:Number(r.produktif)||0,hasData:true,keterangan:r.keterangan,inactiveRecord:true})),[inactive])
 const allPerformanceRows=useMemo(()=>[...activeIndividual,...inactiveRows],[activeIndividual,inactiveRows])
 const selectedRows=useMemo(()=>kanwilFilter==='ALL'?allPerformanceRows:allPerformanceRows.filter(r=>r.kanwil===kanwilFilter),[allPerformanceRows,kanwilFilter])
 const selectedActiveRows=useMemo(()=>kanwilFilter==='ALL'?activeIndividual:activeIndividual.filter(r=>r.kanwil===kanwilFilter),[activeIndividual,kanwilFilter])
 const selectedAllRows=selectedRows
 const filtered=useMemo(()=>selectedAllRows.filter(r=>(status==='ALL'||r.status===status)&&(!search||String(r.nama).toLowerCase().includes(search.toLowerCase()))).slice().sort((a,b)=>{const ai=String(a.status||'').toLowerCase()==='aktif'?1:0,bi=String(b.status||'').toLowerCase()==='aktif'?1:0;return bi-ai || Number(b[metric]||0)-Number(a[metric]||0)}),[selectedAllRows,status,search,metric])
 const aggregate=useMemo(()=>selectedRows.reduce((a,r)=>({pokok:a.pokok+r.pokok,pnbp:a.pnbp+r.pnbp,frekuensi:a.frekuensi+r.frekuensi,lot:a.lot+r.lot}),{pokok:0,pnbp:0,frekuensi:0,lot:0}),[selectedRows])
 const target=useMemo(()=>{const rows=kanwilFilter==='ALL'?targets:targets.filter(t=>t.kanwil===kanwilFilter);return rows.reduce((a,r)=>({pokok:a.pokok+(Number(r.target_pokok)||0),pnbp:a.pnbp+(Number(r.target_pnbp)||0)}),{pokok:0,pnbp:0})},[targets,kanwilFilter])
 const kanwilRows=useMemo(()=>targets.map(t=>{const rows=allPerformanceRows.filter(r=>r.kanwil===t.kanwil);const activeRows=activeIndividual.filter(r=>r.kanwil===t.kanwil);const pokok=rows.reduce((s,r)=>s+r.pokok,0),pnbp=rows.reduce((s,r)=>s+r.pnbp,0),frekuensi=rows.reduce((s,r)=>s+r.frekuensi,0),lot=rows.reduce((s,r)=>s+r.lot,0);return {...t,jumlah_pl2:activeRows.length,realisasi_pokok:pokok,realisasi_pnbp:pnbp,frekuensi,lot,capaian_pokok:Number(t.target_pokok)?pokok/Number(t.target_pokok):0,capaian_pnbp:Number(t.target_pnbp)?pnbp/Number(t.target_pnbp):0,produktif:frekuensi?lot/frekuensi:0}}).filter(r=>kanwilFilter==='ALL'||r.kanwil===kanwilFilter).sort((a,b)=>{const key=chartMode==='pokok'?'capaian_pokok':chartMode==='pnbp'?'capaian_pnbp':'produktif';return Number(b[key]||0)-Number(a[key]||0)}),[targets,allPerformanceRows,activeIndividual,kanwilFilter,chartMode])
 const readout=useMemo(()=>{const all=kanwilRows;const topP=selectedActiveRows.slice().sort((a,b)=>b.pokok-a.pokok)[0],topN=selectedActiveRows.slice().sort((a,b)=>b.pnbp-a.pnbp)[0],bestProd=all.slice().sort((a,b)=>b.produktif-a.produktif)[0],bestPok=all.slice().sort((a,b)=>b.capaian_pokok-a.capaian_pokok)[0],bestPnbp=all.slice().sort((a,b)=>b.capaian_pnbp-a.capaian_pnbp)[0],bestVal=selectedActiveRows.filter(r=>r.frekuensi>0).slice().sort((a,b)=>(b.pokok/b.frekuensi)-(a.pokok/a.frekuensi))[0];return [
 ['Capaian Pokok terbaik',bestPok?`${bestPok.kanwil} · ${pct(bestPok.capaian_pokok)}`:'-'],['Capaian PNBP terbaik',bestPnbp?`${bestPnbp.kanwil} · ${pct(bestPnbp.capaian_pnbp)}`:'-'],['Produktivitas agregat tertinggi',bestProd?`${bestProd.kanwil} · ${bestProd.produktif.toFixed(1)} lot/frek`:'-'],['PL-II Pokok tertinggi',topP?`${topP.nama} · ${shortRp(topP.pokok)}`:'-'],['PL-II PNBP tertinggi',topN?`${topN.nama} · ${shortRp(topN.pnbp)}`:'-'],['Nilai per frekuensi tertinggi',bestVal?`${bestVal.nama} · ${rupiah(bestVal.pokok/bestVal.frekuensi)}/frek`:'-']
 ]},[kanwilRows,selectedActiveRows])
 const top10=useMemo(()=>selectedActiveRows.filter(r=>r.hasData).slice().sort((a,b)=>Number(b[metric]||0)-Number(a[metric]||0)).slice(0,10),[selectedActiveRows,metric])
 const maxTop=Math.max(...top10.map(r=>Number(r[metric]||0)),1)
 const maxKanwil=Math.max(...kanwilRows.map(r=>Number(r[chartMode==='pokok'?'capaian_pokok':chartMode==='pnbp'?'capaian_pnbp':'produktif'])||0),1)
 const counts=(seed.counts as any)[channelYear]||{},channelTotal=Object.values(counts as Record<string,number>).reduce((a,b)=>a+Number(b||0),0)
 const formasi=seed.formasi as any[],fs=seed.formasi_summary as any
 const hist=useMemo(()=>{const rows=[...(seed.hist as any[])]; return rows.sort((a,b)=>{if(histSort==='kanwil'){const c=String(a.kanwil||'').localeCompare(String(b.kanwil||''),'id'); return histDesc?-c:c} const map:any={pokok2023:['y2023','pokok'],pnbp2023:['y2023','pnbp'],pokok2024:['y2024','pokok'],pnbp2024:['y2024','pnbp'],pokok2025:['y2025','pokok'],pnbp2025:['y2025','pnbp']}; const [yr,key]=map[histSort]; const av=Number(a[yr]?.[key])||0,bv=Number(b[yr]?.[key])||0; return histDesc?bv-av:av-bv})},[histSort,histDesc])
 const activeCount=selectedActiveRows.length
 const withDataCount=selectedActiveRows.filter(r=>r.hasData).length
 const inactiveSelectedCount=selectedRows.filter(r=>r.inactiveRecord).length
 const nihilCount=Math.max(activeCount-withDataCount,0)
 const cp=target.pokok?aggregate.pokok/target.pokok:0,cn=target.pnbp?aggregate.pnbp/target.pnbp:0,prod=aggregate.frekuensi?aggregate.lot/aggregate.frekuensi:0
 const metricLabel=metric==='pokok'?'Pokok':metric==='pnbp'?'PNBP':metric==='frekuensi'?'Frekuensi':'Lot'
 const chartValue=(r:any)=>chartMode==='pokok'?Number(r.capaian_pokok)||0:chartMode==='pnbp'?Number(r.capaian_pnbp)||0:Number(r.produktif)||0
 const fmtMetric=(v:number)=>metric==='pokok'||metric==='pnbp'?rupiah(v):num(v)

 return <main className="container">
  <div className="topbar"><div className="title">Executive Dashboard — Pejabat Lelang Kelas II</div><div className="sub">Realisasi s.d. Juli 2026 · diperbaharui 31 Agustus 2026</div><div className="toolbar"><select value={kanwilFilter} onChange={e=>setKanwilFilter(e.target.value)}><option value="ALL">Semua Kanwil</option>{kanwilList.map(k=><option key={k}>{k}</option>)}</select><select value={metric} onChange={e=>setMetric(e.target.value as SortKey)}><option value="pokok">Urutkan: Pokok Lelang</option><option value="pnbp">Urutkan: PNBP Bea Lelang</option><option value="frekuensi">Urutkan: Frekuensi</option><option value="lot">Urutkan: Lot</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Semua Status</option><option value="Aktif">Aktif</option><option value="Tidak Aktif">Tidak aktif</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama PL-II"/></div></div>
  {error&&<div className="notice danger">Gagal membaca sebagian data: {error}</div>}{loading&&<div className="loading">Memuat data live dari Supabase…</div>}
  <div className="kpis"><div className="card kpi"><div className="label">Pokok Lelang</div><div className="value">{shortRp(aggregate.pokok)}</div><div className="meta">Target {shortRp(target.pokok)} · {pct(cp)}</div><div className="progress"><div style={{width:`${Math.min(cp*100,100)}%`}}/></div></div><div className="card kpi"><div className="label">PNBP Bea Lelang</div><div className="value">{shortRp(aggregate.pnbp)}</div><div className="meta">Target {shortRp(target.pnbp)} · {pct(cn)}</div><div className="progress"><div style={{width:`${Math.min(cn*100,100)}%`}}/></div></div><div className="card kpi"><div className="label">Frekuensi Lelang</div><div className="value">{num(aggregate.frekuensi)}</div><div className="meta">{num(withDataCount)} PL-II terdata · {num(aggregate.lot)} lot</div><div className="progress"><div style={{width:`${Math.min(aggregate.frekuensi/5000*100,100)}%`}}/></div></div><div className="card kpi"><div className="label">PL-II Aktif</div><div className="value">{num(activeCount)}</div><div className="meta">{num(withDataCount)} terdata · {num(nihilCount)} nihil</div><div className="progress"><div style={{width:`${Math.min(activeCount/299*100,100)}%`}}/></div></div><div className="card kpi"><div className="label">Produktivitas Operasional</div><div className="value">{prod.toFixed(1)} lot/frek</div><div className="meta">Berdasarkan Lot ÷ Frekuensi</div><div className="progress"><div style={{width:`${Math.min(prod/200*100,100)}%`}}/></div></div></div>

  <div className="grid2"><div className="card"><div className="section-title">Kinerja Agregat per Kanwil</div><div className="tabs"><button className={chartMode==='pokok'?'tab active':'tab'} onClick={()=>setChartMode('pokok')}>Capaian Pokok</button><button className={chartMode==='pnbp'?'tab active':'tab'} onClick={()=>setChartMode('pnbp')}>Capaian PNBP</button><button className={chartMode==='produktif'?'tab active':'tab'} onClick={()=>setChartMode('produktif')}>Produktivitas</button></div><div className="chart-wrap">{kanwilRows.map((r,i)=>{const v=chartValue(r);return <div className="bar-row" key={r.kanwil}><div className="bar-label" title={r.kanwil}>{i+1}. {r.kanwil}</div><div className="bar-track"><div className={`bar ${chartMode==='pnbp'?'green':''}`} style={{width:`${Math.max(Math.min(v/maxKanwil*100,100),2)}%`}}/></div><div className="bar-value">{chartMode==='produktif'?v.toFixed(1):pct(v)}</div></div>})}</div></div><div className="card"><div className="section-title">Read-out Pimpinan</div><div className="insights">{readout.map(([a,b])=><div className="insight" key={a}><b>{a}</b>{b}</div>)}</div><div className="footnote">Fokus dashboard: nilai Pokok Lelang, PNBP Bea Lelang, frekuensi, dan produktivitas PL-II.</div></div></div>

  <div className="grid2"><div className="card"><div className="section-title">Top 10 Pejabat Lelang Kelas II</div><div className="chart-wrap">{top10.map((r,i)=><div className="bar-row" key={r.id}><div className="bar-label" title={r.nama}>{i+1}. {r.nama}</div><div className="bar-track"><div className="bar" style={{width:`${Math.max(Number(r[metric]||0)/maxTop*100,2)}%`}}/></div><div className="bar-value">{fmtMetric(Number(r[metric]||0))}</div></div>)}</div></div><div className="card"><div className="section-title">Ranking PL-II</div><div className="table-wrap"><table><thead><tr><th>#</th><th>Pejabat</th><th>Kanwil</th><th>Pokok</th><th>PNBP</th><th>Frek.</th><th>Lot</th></tr></thead><tbody>{filtered.slice(0,20).map((r,i)=><tr key={r.id} className={r.inactiveRecord?'row-inactive':''}><td>{i+1}</td><td><b>{r.nama}</b></td><td>{r.kanwil}</td><td>{rupiah(r.pokok)}</td><td>{rupiah(r.pnbp)}</td><td>{num(r.frekuensi)}</td><td>{num(r.lot)}</td></tr>)}</tbody></table></div></div></div>

  <div className="card"><div className="section-title">Ringkasan Kanwil</div><div className="table-wrap"><table><thead><tr><th>Kanwil</th><th>PL-II</th><th>Target Pokok</th><th>Realisasi Pokok</th><th>Capaian</th><th>Target PNBP</th><th>Realisasi PNBP</th><th>Capaian</th><th>Frek.</th><th>Produktivitas</th></tr></thead><tbody>{kanwilRows.map(r=><tr key={r.kanwil}><td><b>{r.kanwil}</b></td><td>{num(r.jumlah_pl2)}</td><td>{rupiah(r.target_pokok)}</td><td>{rupiah(r.realisasi_pokok)}</td><td><span className={`badge ${r.capaian_pokok>=1?'good':r.capaian_pokok>=.8?'mid':'low'}`}>{pct(r.capaian_pokok)}</span></td><td>{rupiah(r.target_pnbp)}</td><td>{rupiah(r.realisasi_pnbp)}</td><td><span className={`badge ${r.capaian_pnbp>=1?'good':r.capaian_pnbp>=.8?'mid':'low'}`}>{pct(r.capaian_pnbp)}</span></td><td>{num(r.frekuensi)}</td><td>{r.produktif.toFixed(1)}</td></tr>)}</tbody></table></div><div className="footnote">Realisasi Kanwil dihitung sebagai <b>SUM data PL-II individual</b>; target tetap memakai target Kanwil. Selisih sumber tidak dialokasikan ke individu.</div></div>

  <div className="grid2"><div className="card"><div className="section-title">Profil Penyelenggaraan Lelang — 2024 vs 2025</div><div className="tabs"><button className={channelYear==='2025'?'tab active':'tab'} onClick={()=>setChannelYear('2025')}>2025</button><button className={channelYear==='2024'?'tab active':'tab'} onClick={()=>setChannelYear('2024')}>2024</button></div><div className="pies"><Pie title="Frekuensi" kantor={Number((seed.overall as any)[channelYear]?.kantor_frek)||0} balai={Number((seed.overall as any)[channelYear]?.balai_frek)||0}/><Pie title="Nilai Pokok" kantor={Number((seed.overall as any)[channelYear]?.kantor_pokok)||0} balai={Number((seed.overall as any)[channelYear]?.balai_pokok)||0} money/></div><div className="footnote">Pie menunjukkan share aktivitas melalui Kantor PL-II vs Balai Lelang. PL-II yang menggunakan kedua kanal tetap masuk ke kedua kanal.</div></div><div className="card"><div className="section-title">Profil PL-II berdasarkan Kanal</div><div className="channel"><div className="donut" style={{background:`conic-gradient(#1f6e9e 0 ${(Number(counts['Kantor PL-II'])||0)/channelTotal*100}%,#4e9b73 ${(Number(counts['Kantor PL-II'])||0)/channelTotal*100}% ${(Number(counts['Kantor PL-II'])+Number(counts['Balai Lelang']))/channelTotal*100}%,#c88b35 ${(Number(counts['Kantor PL-II'])+Number(counts['Balai Lelang']))/channelTotal*100}% ${(Number(counts['Kantor PL-II'])+Number(counts['Balai Lelang'])+Number(counts['Keduanya']))/channelTotal*100}%,#b65b62 ${(Number(counts['Kantor PL-II'])+Number(counts['Balai Lelang'])+Number(counts['Keduanya']))/channelTotal*100}% 100%)`}}><div><b>{num(channelTotal)}</b><small>PL-II</small></div></div><div className="legend-list">{[['Kantor PL-II','#1f6e9e'],['Balai Lelang','#4e9b73'],['Keduanya','#c88b35'],['Nihil','#b65b62']].map(([n,c])=><div key={n as string}><i style={{background:c as string}}/><span>{n}</span><b>{num(Number(counts[n as string])||0)}</b></div>)}</div></div><div className="footnote">Kategori jumlah PL-II bersifat eksklusif: Kantor PL-II saja, Balai Lelang saja, Keduanya, atau Nihil.</div></div></div>

  <div className="card"><div className="section-title">Perbandingan Formasi PL-II — KMK 85 vs Kondisi Aktif 25 Agustus 2026</div><div className="formasi-summary"><div className="mini"><span>Formasi</span><b>{num(fs.formasi)}</b></div><div className="mini"><span>Aktif</span><b>{num(fs.aktif)}</b></div><div className="mini"><span>Gap</span><b>{num(Math.abs(fs.gap))}</b></div><div className="mini"><span>Capaian</span><b>{pct(fs.capaian)}</b></div></div><div className="chart-wrap">{formasi.map(r=><div className="bar-row" key={r.kanwil}><div className="bar-label"><b>{r.kanwil}</b></div><div className="bar-track"><div className="bar" style={{width:`${Math.min(Number(r.formasi)?Number(r.aktif)/Number(r.formasi)*100:0,100)}%`}}/></div><div className="bar-value">{num(r.aktif)}/{num(r.formasi)}</div></div>)}</div><div className="footnote">Lokasi aktif 0: {formasi.filter(r=>Number(r.aktif)===0).map(r=>r.kanwil).join(' · ')||'Tidak ada'}.</div></div>

  <div className="card"><div className="section-title">Kinerja Individual PL-II — Juli 2026</div><div className="table-wrap"><table><thead><tr><th>#</th><th>Pejabat</th><th>Kanwil</th><th>Wilayah Jabatan</th><th>Pokok</th><th>PNBP</th><th>Frek.</th><th>Lot</th><th>Prod.</th><th>Status</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id} className={r.inactiveRecord?'row-inactive':(!r.hasData?'row-nihil':'')}><td>{i+1}</td><td><b>{r.nama}</b></td><td>{r.kanwil}</td><td>{r.wilayah_jabatan||'-'}</td><td>{rupiah(r.pokok)}</td><td>{rupiah(r.pnbp)}</td><td>{num(r.frekuensi)}</td><td>{num(r.lot)}</td><td>{r.frekuensi?(r.lot/r.frekuensi).toFixed(1):'0.0'}</td><td><span className={`badge ${r.inactiveRecord?'low':(r.hasData?'good':'low')}`}>{r.inactiveRecord?'Tidak Aktif':(r.hasData?'Ada capaian':'Nihil')}</span></td></tr>)}</tbody></table></div><div className="footnote">Menampilkan {num(filtered.length)} dari {num(selectedRows.length)} PL-II ({num(activeCount)} aktif · {num(inactiveSelectedCount)} tidak aktif dari resume) pada filter saat ini.</div></div>



  <div className="card"><div className="section-title">Capaian Kinerja 3 Tahun — 2023–2025</div><div className="sorts">{[['kanwil','Wilayah'],['pokok2023','Pokok 2023'],['pnbp2023','PNBP 2023'],['pokok2024','Pokok 2024'],['pnbp2024','PNBP 2024'],['pokok2025','Pokok 2025'],['pnbp2025','PNBP 2025']].map(([k,label])=><button key={k} className={histSort===k?'tab active':'tab'} onClick={()=>{setHistSort(k as any);setHistDesc(histSort===k?!histDesc:false)}}>{label} {histSort===k?(histDesc?'↓':'↑'):''}</button>)}</div><div className="table-wrap"><table><thead><tr><th>#</th><th>Pejabat</th><th>Wilayah/Kanwil</th><th>2023 Pokok</th><th>2023 PNBP</th><th>2023 Frek.</th><th>2024 Pokok</th><th>2024 PNBP</th><th>2024 Frek.</th><th>2025 Pokok</th><th>2025 PNBP</th></tr></thead><tbody>{hist.map((r,i)=><tr key={`${r.nama}-${i}`}><td>{i+1}</td><td><b>{r.nama}</b></td><td>{r.kanwil}</td><td>{rupiah(r.y2023?.pokok)}</td><td>{rupiah(r.y2023?.pnbp)}</td><td>{num(r.y2023?.frekuensi)}</td><td>{rupiah(r.y2024?.pokok)}</td><td>{rupiah(r.y2024?.pnbp)}</td><td>{num(r.y2024?.frekuensi)}</td><td>{rupiah(r.y2025?.pokok)}</td><td>{rupiah(r.y2025?.pnbp)}</td></tr>)}</tbody></table></div><div className="footnote">Sorting tersedia untuk Wilayah/Kanwil serta Pokok dan PNBP masing-masing tahun 2023, 2024, dan 2025. Pada sumber 2025, kolom ke-4 berisi PNBP meskipun header workbook tertulis “Pokok Lelang”; diperlakukan sebagai PNBP berdasarkan struktur dan perbandingan sumber.</div></div>

  <footer className="footnote footer">Basis data aktif dan kinerja 2026 dibaca langsung dari Supabase. Histori 2023–2025, kanal 2024–2025, dan formasi 2026 menggunakan baseline sumber yang telah dikunci.</footer>
 </main>
}

function Pie({title,kantor,balai,money=false}:{title:string,kantor:number,balai:number,money?:boolean}){const total=kantor+balai,p=total?kantor/total*100:0;return <div><div style={{textAlign:'center',fontWeight:700,fontSize:12}}>{title}</div><div className="pie" style={{background:`conic-gradient(#1f6e9e 0 ${p}%,#4e9b73 ${p}% 100%)`}}/><div className="legend"><div><span>Kantor PL-II</span><b>{money?shortRp(kantor):num(kantor)}</b></div><div><span>Balai Lelang</span><b>{money?shortRp(balai):num(balai)}</b></div></div></div>}
